<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Philosophy;

class PhilosophySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            [
                'key' => 'philosophy',
                'title_en' => 'PHILOSOPHY',
                'title_id' => 'FILOSOFI',
                'subtitle_en' => 'Creative Foundation',
                'subtitle_id' => 'Fondasi Pemikiran Kreatif',
                'icon' => 'bi-lightbulb-fill',
                'description_en' => 'Our philosophy views design not just as static aesthetics, but as a deep cognitive bridge connecting brand messaging with audience perception.',
                'description_id' => 'Filosofi kami memandang desain bukan sekadar estetika visual statis, melainkan jembatan kognitif mendalam yang menyatukan pesan brand dengan persepsi audiens.',
                'is_highlighted' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'collective',
                'title_en' => 'Collective',
                'title_id' => 'Kolektif',
                'subtitle_en' => 'Synergy of Team & Clients',
                'subtitle_id' => 'Kekuatan Sinergi Tim & Klien',
                'icon' => 'bi-people-fill',
                'description_en' => 'Great ideas are born from collective collaboration. We bring diverse perspectives together to create powerful, market-relevant strategies.',
                'description_id' => 'Ide-ide besar lahir dari kolaborasi kolektif. Kami menyatukan perspektif beragam untuk menghasilkan strategi yang kuat dan relevan bagi pasar.',
                'is_highlighted' => false,
                'sort_order' => 2,
            ],
            [
                'key' => 'mental',
                'title_en' => 'Mental',
                'title_id' => 'Mental',
                'subtitle_en' => 'Mindset & Creative Agility',
                'subtitle_id' => 'Kesiapan & Ketahanan Pola Pikir',
                'icon' => 'bi-heart-pulse-fill',
                'description_en' => 'Building mental agility to stay receptive to new challenges, future creative trends, and out-of-the-box solutions.',
                'description_id' => 'Membangun ketajaman mental untuk selalu terbuka terhadap tantangan baru, tren kreatif masa depan, dan solusi out-of-the-box.',
                'is_highlighted' => false,
                'sort_order' => 3,
            ],
            [
                'key' => 'think',
                'title_en' => 'Think',
                'title_id' => 'Pikir',
                'subtitle_en' => 'Analytical & Strategic Thinking',
                'subtitle_id' => 'Proses Analitis & Strategis',
                'icon' => 'bi-gear-wide-connected',
                'description_en' => 'Before executing visuals, we think deeply about business goals, audience personas, and brand differentiation.',
                'description_id' => 'Sebelum mengeksekusi visual, kami berpikir secara mendalam mengenai tujuan bisnis, persona target audiens, dan diferensiasi brand Anda.',
                'is_highlighted' => false,
                'sort_order' => 4,
            ],
            [
                'key' => 'cognitive',
                'title_en' => 'Cognitive',
                'title_id' => 'Kognitif',
                'subtitle_en' => 'Perception & Memory Response',
                'subtitle_id' => 'Respons Persepsi & Memori',
                'icon' => 'bi-cpu-fill',
                'description_en' => 'Understanding how audiences capture, process, and retain your message through structured visual hierarchy and brand narrative.',
                'description_id' => 'Memahami bagaimana audiens menangkap, memproses, dan mengingat pesan Anda melalui hierarki visual dan narasi brand yang terarah.',
                'is_highlighted' => false,
                'sort_order' => 5,
            ],
            [
                'key' => 'mind',
                'title_en' => 'MIND',
                'title_id' => 'PIKIRAN',
                'subtitle_en' => 'Limitless Exploration',
                'subtitle_id' => 'Ruang Eksplorasi Tanpa Batas',
                'icon' => 'bi-stars',
                'description_en' => 'The mind is the laboratory where wild imagination is distilled into high-impact commercial concepts with real results.',
                'description_id' => 'Pikiran adalah laboratorium tempat imajinasi liar diramu menjadi konsep komersial yang berdaya tarik tinggi dan menghasilkan dampak nyata.',
                'is_highlighted' => true,
                'sort_order' => 6,
            ],
            [
                'key' => 'problem',
                'title_en' => 'Problem',
                'title_id' => 'Masalah',
                'subtitle_en' => 'Catalyst for Innovation',
                'subtitle_id' => 'Peluang untuk Inovasi',
                'icon' => 'bi-patch-question-fill',
                'description_en' => 'We do not avoid market problems; we dissect them to find the best creative angles that solve your brand barriers.',
                'description_id' => 'Kami tidak menghindari masalah pasar; kami membedahnya untuk menemukan sudut pandang kreatif terbaik yang memecahkan hambatan brand Anda.',
                'is_highlighted' => false,
                'sort_order' => 7,
            ],
            [
                'key' => 'psychology',
                'title_en' => 'Psychology',
                'title_id' => 'Psikologi',
                'subtitle_en' => 'Consumer Emotional Touch',
                'subtitle_id' => 'Sentuhan Emosional Konsumen',
                'icon' => 'bi-person-heart',
                'description_en' => 'Analyzing consumer behavior, emotion, and psychological motivation to create campaigns that resonate deeply and trigger action.',
                'description_id' => 'Menganalisis perilaku, emosi, dan motivasi psikologis konsumen untuk menciptakan kampanye yang menyentuh hati dan menggerakkan tindakan.',
                'is_highlighted' => false,
                'sort_order' => 8,
            ],
            [
                'key' => 'human',
                'title_en' => 'Human',
                'title_id' => 'Manusia',
                'subtitle_en' => 'Human-Centric Approach',
                'subtitle_id' => 'Pendekatan Human-Centric',
                'icon' => 'bi-person-badge',
                'description_en' => 'The best designs are human-centric. We craft work that is intuitive, empathetic, and meaningful in everyday life.',
                'description_id' => 'Desain terbaik berpusat pada manusia. Kami menciptakan karya yang ramah, berempati, dan bermakna bagi kehidupan sehari-hari.',
                'is_highlighted' => false,
                'sort_order' => 9,
            ],
            [
                'key' => 'brain',
                'title_en' => 'BRAIN',
                'title_id' => 'OTAK',
                'subtitle_en' => 'Logic & Creative Artistry',
                'subtitle_id' => 'Integrasi Logika & Seni Kreatif',
                'icon' => 'bi-diagram-3-fill',
                'description_en' => 'Harmoniously balancing left-brain logic (data analysis, business calculation) with right-brain artistry (art aesthetics, visual emotion).',
                'description_id' => 'Menyeimbangkan fungsi otak kiri (analisis data, kalkulasi bisnis) dan otak kanan (estetika seni, emosi visual) secara harmonis.',
                'is_highlighted' => true,
                'sort_order' => 10,
            ],
            [
                'key' => 'neurons',
                'title_en' => 'Neurons',
                'title_id' => 'Neuron',
                'subtitle_en' => 'Spark of Idea Connections',
                'subtitle_id' => 'Percikan Koneksi Ide',
                'icon' => 'bi-lightning-charge-fill',
                'description_en' => 'Each neuron represents a synapse of creative ideas interconnecting to form a comprehensive campaign ecosystem (ATL, BTL & Digital).',
                'description_id' => 'Setiap neuron merepresentasikan sinapsis ide kreatif yang saling terhubung membentuk kesatuan kampanye komprehensif (ATL, BTL & Digital).',
                'is_highlighted' => false,
                'sort_order' => 11,
            ],
            [
                'key' => 'body',
                'title_en' => 'Body',
                'title_id' => 'Tubuh',
                'subtitle_en' => 'Physical Execution & Touchpoint',
                'subtitle_id' => 'Realisasi & Eksekusi Nyata',
                'icon' => 'bi-activity',
                'description_en' => 'Great concepts demand solid real-world execution—from premium print materials to physical field activations.',
                'description_id' => 'Konsep hebat memerlukan eksekusi nyata yang solid—mulai dari materi cetak berkualitas premium hingga aktivasi fisik di lapangan.',
                'is_highlighted' => false,
                'sort_order' => 12,
            ],
            [
                'key' => 'ego',
                'title_en' => 'Ego',
                'title_id' => 'Ego',
                'subtitle_en' => 'Unique Brand Character',
                'subtitle_id' => 'Karakter & Diferensiasi Brand',
                'icon' => 'bi-shield-shaded',
                'description_en' => 'Building a bold and distinctive brand character that stands out with confidence and strong differentiation in competitive markets.',
                'description_id' => 'Membangun karakter dan ciri khas brand yang berani tampil beda, percaya diri, dan memiliki diferensiasi kuat di pasar kompetitif.',
                'is_highlighted' => false,
                'sort_order' => 13,
            ],
            [
                'key' => 'individual',
                'title_en' => 'Individual',
                'title_id' => 'Individu',
                'subtitle_en' => 'Tailored Bespoke Solutions',
                'subtitle_id' => 'Sentuhan Personal & Kustom',
                'icon' => 'bi-person-check-fill',
                'description_en' => 'Every brand and client is unique. We provide tailored approaches crafted specifically to your unique requirements.',
                'description_id' => 'Setiap brand dan klien memiliki keunikan tersendiri. Kami menyediakan pendekatan yang dipersonalisasi sesuai kebutuhan spesifik Anda.',
                'is_highlighted' => false,
                'sort_order' => 14,
            ],
            [
                'key' => 'see',
                'title_en' => 'See',
                'title_id' => 'Lihat',
                'subtitle_en' => 'Vision & Fresh Perspectives',
                'subtitle_id' => 'Visi & Perspektif Masa Depan',
                'icon' => 'bi-eye-fill',
                'description_en' => 'Looking beyond standard industry boundaries—discovering fresh perspectives that keep your brand ahead of the curve.',
                'description_id' => 'Melihat melampaui batas standar industri—menemukan sudut pandang baru yang membuat brand Anda selalu relevan dan terdepan.',
                'is_highlighted' => false,
                'sort_order' => 15,
            ],
        ];

        foreach ($items as $item) {
            Philosophy::updateOrCreate(['key' => $item['key']], $item);
        }
    }
}
